name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: "Flatpak branch to use for build."
        required: false
        type: string
        default: "beta"

jobs:
  flatpak-build:
    name: "Verify Flatpak Build"
    permissions:
      contents: read
    uses: ./.github/workflows/build-flatpak.yml
    with:
      branch: ${{ inputs.branch || 'beta' }}
      dry-run: true
