name: Release

on:
  workflow_dispatch:

jobs:
  publish:
    name: "Publish to Flatpak Repo"
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    uses: ./.github/workflows/build-flatpak.yml
    with:
      dry-run: false
    secrets:
      gpg-private-key: ${{ secrets.AETHERPAK_GPG_KEY }}
